version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: captely-redis

  db:
    image: postgres:16-alpine
    container_name: captely-db
    env_file: .env
    volumes:
      - captely_db-data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: captely-auth-service
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db, redis]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  import-service:
    build: ./import-service
    container_name: captely-import-service
    env_file: .env
    ports: ["8001:8000"]
    depends_on: [db, redis]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  credit-service:
    build: ./credit-service
    container_name: captely-credit-service
    env_file: .env
    ports: ["8002:8000"]
    depends_on: [db]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  enrichment-worker:
    build: ./enrichment-worker
    container_name: captely-enrichment-worker
    env_file: .env
    depends_on: [redis]
    command: celery -A app.tasks worker --loglevel=info

volumes:
  captely_db-data:
