version: '3.9'
services:
  db:
    image: postgres:14
    container_name: captely_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: captely
    ports:
      - "5432:5432"