services:
  db:
    image: postgres:16-alpine
    environment: &pg_env
      POSTGRES_DB: captely
      POSTGRES_USER: captely
      POSTGRES_PASSWORD: captely
    volumes: [db-data:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  auth-service:
    build: ./services/auth-service
    env_file: ./.env
    depends_on: { db: {condition: service_started} }
    ports: ["8000:8000"]

  import-service:
    build: ./services/import-service
    env_file: ./.env
    depends_on: [db, redis]
    ports: ["8001:8001"]

  enrichment-worker:
    build: ./services/enrichment-service
    env_file: ./.env
    depends_on: [db, redis]

  credit-service:
    build: ./services/credit-service
    env_file: ./.env
    depends_on: [db]
    ports: ["8002:8002"]

volumes: { db-data: {} }
