version: '3.8'

services:

  # ---------- Backend core ----------

  redis:
    image: redis:7-alpine
    container_name: captely-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: captely-db
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB:      ${POSTGRES_DB}
      POSTGRES_USER:    ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - captely_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-service:
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    container_name: captely-auth-service
    env_file:
      - ./backend/.env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    restart: on-failure

  import-service:
    build:
      context: ./backend/services/import-service
      dockerfile: Dockerfile
    container_name: captely-import-service
    env_file:
      - ./backend/.env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    ports:
      - "8002:8000"
    depends_on:
      - db
      - redis
    restart: on-failure

  credit-service:
    build:
      context: ./backend/services/credit-service
      dockerfile: Dockerfile
    container_name: captely-credit-service
    env_file:
      - ./backend/.env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    ports:
      - "8003:8000"
    depends_on:
      - db
      - redis
    restart: on-failure

  enrichment-worker:
    build:
      context: ./backend/services/enrichment-worker
      dockerfile: Dockerfile
    container_name: captely-enrichment-worker
    env_file:
      - ./backend/.env
    command: >
      celery -A common.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    restart: on-failure

  # ---------- Frontend ----------

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: captely-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_AUTH_URL:   http://auth-service:8000
      NEXT_PUBLIC_IMPORT_URL: http://import-service:8000
      NEXT_PUBLIC_CREDIT_URL: http://credit-service:8000
    depends_on:
      - auth-service
      - import-service
      - credit-service
    restart: unless-stopped

volumes:
  captely_db_data:
