services:
  redis:
    image: redis:7-alpine
    container_name: captely-redis
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: captely-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: captely-auth-service
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

  import-service:
    build:
      context: ./import-service
      dockerfile: Dockerfile
    container_name: captely-import-service
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8001:8000"
    env_file:
      - .env

  credit-service:
    build:
      context: ./credit-service
      dockerfile: Dockerfile
    container_name: captely-credit-service
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8002:8000"
    env_file:
      - .env

  enrichment-worker:
    build:
      context: .
      dockerfile: enrichment_worker/Dockerfile
    container_name: captely-enrichment-worker
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    # no ports—this is a background worker

volumes:
  db-data:
