version: "3.8"

services:
  redis:
    image: redis:7.4.2
    ports: ["6379:6379"]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB:   ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports: ["8001:8000"]
    env_file: .env
    depends_on: [ db ]

  import-service:
    build:
      context: .
      dockerfile: services/import-service/Dockerfile
    ports: ["8002:8000"]
    env_file: .env
    depends_on: [ auth-service, db, redis ]

  credit-service:
    build:
      context: .
      dockerfile: services/credit-service/Dockerfile
    ports: ["8003:8000"]
    env_file: .env
    depends_on: [ auth-service, db, redis ]

  enrichment-worker:
    build:
      context: .
      dockerfile: services/enrichment-worker/Dockerfile
    env_file: .env
    depends_on: [ redis, db ]
    command: >
      celery 
      -A services.enrichment-worker.tasks 
      worker --loglevel=info

volumes:
  db-data:
