version: '3.8'

services:

  # Postgres
  db:
    image: postgres:16-alpine
    environment: &pg_env
      POSTGRES_DB: captely
      POSTGRES_USER: captely
      POSTGRES_PASSWORD: captely
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis (for Celery broker/backend)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Auth service
  auth-service:
    build:
      context: ./services/auth-service
    working_dir: /app
    volumes:
      - ./services/common:/app/common
      - ./services/auth-service:/app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8001:8000"

  # Import service (Sales Navigator scraper)
  import-service:
    build:
      context: ./services/import-service
    working_dir: /app
    volumes:
      - ./services/common:/app/common
      - ./services/import-service:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - auth-service
    ports:
      - "8003:8003"

  # Enrichment worker (Celery)
  enrichment-worker:
    build:
      context: ./services/enrichment-worker
    working_dir: /app
    volumes:
      - ./services/common:/app/common
      - ./services/enrichment-worker:/app
    env_file:
      - ./.env
    depends_on:
      - redis
    # point at your tasks module under /app/app/tasks.py
    command: >
      celery -A app.tasks.celery_app worker --loglevel=info

  # Credit service
  credit-service:
    build:
      context: ./services/credit-service
    working_dir: /app
    volumes:
      - ./services/common:/app/common
      - ./services/credit-service:/app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8002:8002"

volumes:
  db-data:
