version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: captely
      POSTGRES_USER: captely
      POSTGRES_PASSWORD: captely
    ports: ["5432:5432"]
    volumes: ["db-data:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  auth-service:
    build: ./services/auth-service
    env_file: ./env/auth.env
    depends_on: [db]
    ports: ["8000:8000"]

  # Les autres services arriveront ensuite
  # import-service:
  # credit-service:
  # enrichment-service:

volumes:
  db-data:
