# docker-compose.local.yml
version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: captely
      POSTGRES_USER: captely
      POSTGRES_PASSWORD: captely_pwd
    volumes:
      - captely_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  captely_db_data:
